### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by tomliversidge** [neverworkintheory/neverworkintheory.github.io#17]
Does the site have any sort of analytics associated with it? I didn't notice anything when poking about in the code. If not, something like google analytics could be added to give visibility of how many people are viewing the site, and which are the most popular articles etc.

**Comment by jorgearanda** [comment]
The site does not have any sort of analytics currently. I'm open to adding them if it's easy with our setup and @gvwilson agrees...

**Comment by tomliversidge** [comment]
As an administrator, do you see anything like this?
https://github.com/blog/1672-introducing-github-traffic-analytics

**Comment by jorgearanda** [comment]
Yes, but it looks like that's for the repo itself, rather than for the content...
![screen shot 2016-06-21 at 5 09 28 pm](https://cloud.githubusercontent.com/assets/730633/16250539/0aad0154-37d3-11e6-8937-d884f476a054.png)

**Comment by tomliversidge** [comment]
O ok, in that case, i think Google Analytics is just one line of JavaScript to add in the header of the page.
