### ISSUE TITLE
Add curated summary pages for certain categories

### ISSUE THREAD

**Issue by tomliversidge** [neverworkintheory/neverworkintheory.github.io#18]
Coming from a professional software developer perspective my interest in this site is from the point of view of wanting to know what evidence there is for certain practices, i.e. Code Reviews, TDD etc.. I'd like to see something similar to the way the book Making Software presented the information. For example, if I'm interested in TDD, I'd like to go to a page where there is a summary of the evidence / literature for this, along with the links to the articles. The new Category view goes someway to adding in this functionality, but still requires someone to read all the individual articles.

The would probably apply more to certain categories than to others, so I'd propose making changes to the Jekyll templates to allow some of the categories to have their own pages, whereas others would just link to the existing categories page. I'd also like to see a drop down menu in the navigation with links to these category summary pages.

**Comment by jorgearanda** [comment]
Would be great to add this. But though templating changes and drop down menus would help, it sounds to me though that the main work needed is the curation itself, or a "guided tour" through papers we've featured per topic, no?

**Comment by tomliversidge** [comment]
Absolutely! The technical bit will be pretty easy, it's the curation that would need time and expertise.
