### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by gvwilson** [neverworkintheory/neverworkintheory.github.io#32]
- https://rashina.com/stgt/
- https://arxiv.org/abs/2108.09905
- https://www.biorxiv.org/content/10.1101/092205v3.abstract
- https://dl.acm.org/doi/10.1145/3468264.3468592
- 10.1109/TSE.2019.2938525
- https://dl.acm.org/doi/10.1145/3468504
- https://dl.acm.org/doi/10.1145/3469888
- https://doi.org/10.1007/s10664-020-09818-7
- https://link.springer.com/article/10.1007/s10664-021-09995-z
- https://link.springer.com/article/10.1007/s10664-021-10007-3
- https://link.springer.com/article/10.1007/s10664-021-10016-2
- https://link.springer.com/article/10.1007/s10664-021-10025-1
- https://www.win.tue.nl/~aserebre/SANER2020Nathan.pdf
- 0.1177/0735633117707312

**Comment by t1ooo** [comment]
https://arxiv.org/abs/2007.09863
